# This is a basic workflow to help you get started with Actions

name: CI

on:
  release:
    types: [published] 

 
jobs:
  build-and-publish-tag:
      runs-on: ubuntu-latest
      if: startsWith(github.ref, 'refs/tags/') # Running this job only for tags

      steps:
      - uses: actions/checkout@v2

      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: ${{ github.repository }} # Provide only Docker image name
          extract-git-tag: true # Provide flag to extract Docker image tag from git reference
